const { createSkhdMode } = require('./createSkhdMode');
const { mapObjIndexed, pipe, values } = require('ramda');
const { createSwitchFocusEntries } = require('./createSwitchFocusEntries');


const convertLayoutsToSkhdEntries = pipe(
  mapObjIndexed((layoutConfig, layoutName) => ({
    triggerKey: layoutConfig.triggerKey,
    actions: [`yco apply-layout --name ${layoutName}`]
  })),
  values
);

exports.getSkhdEntries = ({ ycoConfig }) => {
  let entries = ['# This file was automatically generated by "yco create-configs". Changes will be overwritten.'];

  if (ycoConfig.layouts) {
    entries = [
      ...entries,
      '# LAYOUT MODS',
      ...createSkhdMode({
        name: 'layoutMode',
        triggerKey: ycoConfig.layoutModeTriggerKey,
        entries: convertLayoutsToSkhdEntries(ycoConfig.layouts)
      }),
      '\n'
    ];
  }

  if (ycoConfig.switchFocus) {
    entries = [
      ...entries,
      '# SWITCH FOCUS CONFIGS',
      ...createSwitchFocusEntries({ switchFocusConfigs: ycoConfig.switchFocus }),
      '\n'
    ];
  }

  return entries.join('\n');
};
