const { createSkhdMode } = require('./createSkhdMode');
const { createSwitchFocusEntries } = require('./createSwitchFocusEntries');


const convertLayoutsToSkhdEntries = layouts => layouts.map(layout => ({
  triggerKey: layout.triggerKey,
  actions: [`yco apply-layout --name ${layout.name}`]
}));

exports.getSkhdEntries = ({ ycoConfig }) => {
  let entries = ['# This file was automatically generated by "yco create-configs". Changes will be overwritten.'];

  if (ycoConfig.layouts) {
    entries = [
      ...entries,
      '# LAYOUT MODS',
      ...createSkhdMode({
        name: 'layoutMode',
        triggerKey: ycoConfig.layoutModeTriggerKey,
        entries: convertLayoutsToSkhdEntries(ycoConfig.layouts)
      }),
      '\n'
    ];
  }

  if (ycoConfig.switchFocus) {
    entries = [
      ...entries,
      '# SWITCH FOCUS CONFIGS',
      ...createSwitchFocusEntries({ switchFocusConfigs: ycoConfig.switchFocus }),
      '\n'
    ];
  }

  return entries.join('\n');
};
